# Generated by Django 5.1.4 on 2024-12-12 19:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_subsubcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='lessons/image/')),
                ('video', models.FileField(blank=True, null=True, upload_to='lessons/video/')),
                ('voice', models.FileField(blank=True, null=True, upload_to='lessons/voice/')),
                ('text', models.TextField(blank=True, null=True)),
                ('views', models.IntegerField(default=0)),
                ('date', models.DateField(default=datetime.datetime.now)),
                ('subsubcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subsubcategory')),
            ],
        ),
    ]
