# Generated by Django 5.1.4 on 2024-12-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subsubcategory',
            name='category',
        ),
    ]
