# Generated by Django 5.1.4 on 2024-12-12 19:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_lesson_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.subcategory'),
        ),
    ]
