# Generated by Django 5.1.4 on 2024-12-12 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_subsubcategory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subsubcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.category'),
        ),
    ]
