# Generated by Django 5.1.4 on 2024-12-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_subsubcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='value',
            field=models.IntegerField(default=0),
        ),
    ]
