# Generated by Django 5.1.4 on 2024-12-12 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_lesson_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='subsubcategory',
        ),
        migrations.DeleteModel(
            name='SubSubCategory',
        ),
    ]
