# Generated by Django 5.1.4 on 2024-12-13 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_category_image_remove_subcategory_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='has_tree',
            field=models.BooleanField(default=False),
        ),
    ]
