# Generated by Django 5.1.4 on 2024-12-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_menu_has_tree'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='has_tree',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='has_tree',
            field=models.BooleanField(default=False),
        ),
    ]
