# Generated by Django 5.1.4 on 2024-12-21 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_userlessons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='value',
            field=models.IntegerField(default=0, unique=True),
        ),
    ]
