# Generated by Django 4.2.17 on 2025-02-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_subsubcategory_has_tree_subsubsubcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='main_page',
            field=models.BooleanField(default=True),
        ),
    ]
