# Generated by Django 4.2.17 on 2025-02-06 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_remove_lesson_value'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLessons',
        ),
    ]
