# Generated by Django 4.2.17 on 2025-02-06 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_rename_link_lesson_link_1_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='link_1',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='link_title',
        ),
    ]
